# Generated by Django 4.1.4 on 2022-12-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('To do', 'To do'), ('Completed', 'Completed'), ('Testing', 'Testing'), ('Onhold', 'Onhold')], max_length=50)),
            ],
        ),
    ]
