# Generated by Django 4.1.4 on 2022-12-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_role_master_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_permission_mapping',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user_permission_mapping',
            name='end_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user_permission_mapping',
            name='start_dt',
            field=models.DateField(null=True),
        ),
    ]
