# Generated by Django 4.1.4 on 2022-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_user_active_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_mapping',
            name='navbar_name',
            field=models.CharField(choices=[('Company', 'Company'), ('User', 'User'), ('Role', 'Role'), ('Team member', 'Team member')], max_length=50, null=True),
        ),
    ]
